FROM php:8.2-fpm AS php_base

# Instalar dependencias del sistema
RUN set -eux; \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        acl \
        file \
        gettext \
        git \
        unzip \
        libicu-dev \
        libzip-dev \
        curl \
        ca-certificates \
        gnupg \
        dirmngr \
        && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
        && apt-get install -y nodejs \
        && npm install -g npm@latest \
    && rm -rf /var/lib/apt/lists/*

# Instalar PHP Extension Manager
RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    -o /usr/local/bin/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions

# Instalar extensiones PHP
RUN set -eux; \
    install-php-extensions \
        @composer \
        intl \
        zip \
        pdo_mysql



# Copiar script de arranque
COPY ./docker/scripts/laravel-start.sh /usr/local/bin/laravel-start.sh
RUN chmod +x /usr/local/bin/laravel-start.sh

ENTRYPOINT ["/usr/local/bin/laravel-start.sh"]
HEALTHCHECK --interval=10s --timeout=10s --start-period=30s --retries=10 CMD [ -f /tmp/healthy ] || exit 1
CMD ["sh", "-c", "php-fpm"]
